collection_id: de92de2f-f40b-48ab-bdbc-64d58f72e9d9
name: Noodle Collection
description: This is a sample collection designed to help Noodle developers.
timeline_max_entries: 50
environment: development
proxy:
  mode: inherit
tls:
  verify: true
  client_certificates: []
