[tool.poetry]
name = "noodle"
version = "0.0.3"
description = ""
authors = ["Carlos <carlos@pythoncheatsheet.org>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
